-- Store status (ACTIVE, INACTIVE, PENDING, CLOSED)
ALTER TABLE stores ADD COLUMN IF NOT EXISTS status VARCHAR(255) NULL;

-- Order type (DELIVERY, PICKUP, DINE_IN)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_type VARCHAR(255) NULL;
